[package]
name = "sui_core"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
rocksdb = "0.18.0"
anyhow = "1.0.55"
bcs = "0.1.3"
futures = "0.3.21"
rand = "0.7.3"
bytes = "1.1.0"
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.17.0", features = ["full", "tracing"] }
parking_lot = "0.12.0"
itertools = "0.10.3"
async-trait = "0.1.52"
tempfile = "3.3.0"
tracing = { version = "0.1.31", features = ["log"] }
signature = "1.5.0"
ed25519-dalek = "1.0.1"
scopeguard = "1.1.0"
structopt = "0.3.26"
log = "0.4.14"

sui-adapter = { path = "../sui_programmability/adapter" }
sui-framework = { path = "../sui_programmability/framework" }
sui-network = { path = "../network_utils" }
sui-types = { path = "../sui_types" }

move-binary-format = { git = "https://github.com/diem/move", rev = "63bd52e0f5b02711d29a678e6f946b3d429f2090" }
move-bytecode-utils = { git = "https://github.com/diem/move", rev = "63bd52e0f5b02711d29a678e6f946b3d429f2090" }
move-core-types = { git = "https://github.com/diem/move", rev = "63bd52e0f5b02711d29a678e6f946b3d429f2090", features = ["address20"] }
move-package = { git = "https://github.com/diem/move", rev = "63bd52e0f5b02711d29a678e6f946b3d429f2090" }
move-vm-runtime = { git = "https://github.com/diem/move", rev = "63bd52e0f5b02711d29a678e6f946b3d429f2090" }
move-vm-types = { git = "https://github.com/diem/move", rev = "63bd52e0f5b02711d29a678e6f946b3d429f2090" }

typed-store = { git = "https://github.com/MystenLabs/mysten-infra", rev = "e44bca4513a6ff6c97399cd79e82e4bc00571ac3"}
schemars = "0.8.8"
serde_json = "1.0.79"
hex = "0.4.3"

[dev-dependencies]
fdlimit = "0.2.1"
serde-reflection = "0.3.5"
serde_yaml = "0.8.23"
pretty_assertions = "1.2.0"
temp_testdir = "0.2"

test_utils = { path = "../test_utils" }

[[example]]
name = "generate-format"
path = "src/generate_format.rs"
test = false

[package.metadata.cargo-udeps.ignore]
normal = ["structopt"]
